config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'stories#index'

  resources :stories

end

app/models/story.rb
class Story < ActiveRecord::Base

has_attached_file :image, styles: { medium: "500x500>", thumb: "300x300>" }, default_url: "/images/:style/test.jpg"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

geocoded_by :location
after_validation :geocode


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
    @map_stories = Story.all
  end

  def new
  	@story = Story.new
  end

  def create
  	@story = Story.create(story_params)
  	redirect_to '/stories'
  end

  def show
  	@story = Story.find(params[:id])
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    @story.update(story_params)

    redirect_to '/stories'
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    flash[:notice] = "Story has been deleted successfully"

    redirect_to '/stories'
  end

  def story_params
  	params.require(:story).permit(:title, :article, :image, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoRealism</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <main>

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">PhotoRealism</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><%= link_to "Stories", stories_path %></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
              <% if user_signed_in? %>
              <li><a href="/stories/new">Add a story</a></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
             <% if user_signed_in? %>
                <!-- <li><%= link_to "Tell a Story", new_story_path %></li> -->
                <% else %>
                <!-- <li><%= link_to "Tell a Story", new_user_registration_path  %></li> -->
                <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>


  </main>
</body>
</html>

app/views/stories/edit.html.erb
<%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/stories/index.html.erb
<% if @stories.any? %>
  <% @stories.each do |story| %>
    <h2> <%= link_to "#{story.title}", story_path(story) %> </h2>
    <h4><%= link_to "Edit #{story.title}", edit_story_path(story) %> </h4>
    <h4><%= link_to "Delete #{story.title}", story_path(story), method: :delete %></h4>

   <%= link_to (image_tag "#{story.image.url(:thumb)}"), story_path(story) %>
  <% end %>
<% else %>
  No stories yet!
<% end %>
<div id="map" style="height: 35em;">
  <script>
  	var map;
  	$(document).ready(function(){
      map = new GMaps({
  	  	div: '#map',
  	  	lat: 54,
  	  	lng: -2.5,
        zoom: 2,
        zoomControl: true,
        zoomControlOpt: {
          position: 'LEFT_CENTER'
        },
        scrollwheel: false,
  	  });
  	});
  </script>

</div>

<% if @map_stories.any? %>
  <% @map_stories.each do |story| %>

    <%= javascript_tag do %>
      $(document).ready(function(){
          map.addMarker({
            lat: <%= story.latitude %>,
            lng: <%= story.longitude %>,
            title: 'Lima',
              infoWindow: { content: '<%= story.title %></br><%= image_tag story.image.url(:thumb) %>' },
              click: function(e) {

              }
          });
        });
    <% end %>
  <% end %>
    <% else %>
      <h1>No stories yet!</h1>
  <% end %>

app/views/stories/new.html.erb
<%= form_for @story, html: {multipart: true} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :article, 'Story' %>
	<%= f.text_area :article %>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<%= f.file_field :image %>
	<%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<p><%= @story.title %><p>

<%= image_tag @story.image.url(:medium) %>
<%= @story.article %>
<%= @story.location %>